# Build, test, and deploy the content hub.
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/php
#=========================================================================
# In addition to the environment variables defined in this file, also
# add the following variables in the Azure Pipelines UI.
#
# See: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
#
#   terminus.site: Drupal site for running Selenium tests
#   test.site.username: Username for logging into Drupal site (secret)
#   test.site.password: Password for logging into Drupal site (secret)
#
# Under variable groups, create a variable group called "ugconthub-gatsby-variables"
#
#   PantheonSiteLabel: Affiliated Pantheon site e.g. "bovey"
#   ServiceConnection: Our Azure service connection (set up on Azure)
#   Site: Affiliated Front-end site e.g. ugconthub
#   Zone: Affiliated domain zone e.g. uoguelph.dev
#   terminus.token: The Pantheon machine token
#
#=========================================================================

variables:
  phpVersion: 7.2
  TestQAUsername: $(test.site.username)
  TestQAPassword: $(test.site.password)
  _service_connection: $(ServiceConnection)
  _gatsby_folder: '.ci/gus'
  _gatsby_cache_folder: '.ci/gus/.cache'
  _gatsby_public_folder: '.ci/gus/public'
  _site: $(Site)
  _zone: $(Zone)

trigger:
- develop

pr:
- develop
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- checkout: self
  persistCredentials: true

- script: ./.ci/env/set
  displayName: 'Install backend build tools'

- script: ./.ci/env/set-tests
  displayName: 'Install backend test tools'

# Build Assets (Composer Install)
- script: ./.ci/build/php
  displayName: 'Install Drupal with composer'

# - script: ./.ci/deploy/pantheon/dev-multidev
#   displayName: 'Deploy to Pantheon CI Multidev for Testing'
#   condition: succeeded()

# Run Selenium Tests
# - task: NuGetAuthenticate@0
#   displayName: '[Selenium] Authenticate to get packages'
#   condition: succeeded()
#   inputs:
#     nuGetServiceConnections: DrupalTestServiceConnection

# - task: DotNetCoreCLI@2
#   displayName: '[Selenium] Restore packages'
#   condition: succeeded()
#   inputs:
#     command: restore
#     projects: '$(Build.SourcesDirectory)/tests/selenium/**/*.csproj'
#     feedsToUse: select
#     vstsFeed: 'CCS/DrupalTest'
#     includeNuGetOrg: true

# - task: FileTransform@1
#   displayName: '[Selenium] Replace site-specific tokens in appsettings.json'
#   condition: succeeded()
#   inputs:
#     folderPath: '$(Build.SourcesDirectory)/tests/selenium/BoveyTest'
#     fileType: json
#     targetFiles: appsettings.json

# - task: DotNetCoreCLI@2
#   displayName: '[Selenium] Run tests'
#   condition: succeeded()
#   inputs:
#     command: test
#     projects: '$(Build.SourcesDirectory)/tests/selenium/**/*.csproj'
#     publishTestResults: true

# Deploy to Upstream
# - script: ./.ci/deploy/github/upstream
#   displayName: 'Deploy to upstream'
#   condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/develop'))

# Deploy upstream to Bovey Dev
- script: ./.ci/deploy/pantheon/dev
  displayName: 'Deploy to Pantheon Bovey dev'
  condition: succeeded()

# Prepare for Gatsby builds
- script: ./.ci/env/set
  workingDirectory: $(_gatsby_folder)
  displayName: 'Initialize frontend build tools'
  condition: succeeded()

- script: 'npm install --only=dev gatsby-cli'
  workingDirectory: $(_gatsby_folder)
  displayName: 'Install Gatsby-CLI'
  condition: succeeded()

- task: Npm@1
  displayName: 'npm install'
  condition: succeeded()
  inputs:
    workingDir: $(_gatsby_folder)
    verbose: false

# Output Dev environment variables for gus and azure
- bash: |
    echo "##vso[task.setvariable variable=_gatsby_source]dev"
    echo "##vso[task.setvariable variable=_env]solo"
  displayName: 'Set environment to SOLO'
  condition: succeeded()

# Prepare to deploy
- script: ./.ci/deploy/azure/set
  displayName: 'Prep variables for Azure deployment'
  condition: succeeded()

# Retrieve caches
- task: CacheBeta@1
  inputs:
    key: 'gatsby_cache | "$(Agent.OS)" | "$(Build.SourceBranch)" | "$(_site)" | "$(_zone)"'
    path: $(_gatsby_cache_folder)
  displayName: 'Retrieve cached Gatsby .cache folder'

- task: CacheBeta@1
  inputs:
    key: 'gatsby_public | "$(Agent.OS)" | "$(Build.SourceBranch)" | "$(_site)" | "$(_zone)"'
    path: $(_gatsby_public_folder)
  displayName: 'Retrieve cached Gatsby public folder'

# Build Gatsby (Drupal Source = Bovey Dev) using submodule of gus
- script: |
    npx gatsby build --prefix-paths
  workingDirectory: $(_gatsby_folder)
  displayName: 'Gatsby build (Dev)'
  condition: succeeded()

# Deploy built artifact from gatsby build to azure (Dev)
- task: "AzureResourceGroupDeployment@2"
  displayName: 'Create or update resource group'
  inputs:
    azureSubscription: '$(_service_connection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(_rg_name)'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(_gatsby_folder)/azuredeploy.json'
    overrideParameters: '-env $(_env) -site $(_site) -zone $(_zone) -pantheonsitelabel $(_pantheonsitelabel)'
    deploymentMode: 'Complete'
    deploymentOutputs: 'outputConnectionString'

- task: AzureCLI@1
  displayName: 'Enable custom https using CDN Managed certificate'
  inputs:
    azureSubscription: '$(_service_connection)'
    scriptLocation: 'inlineScript'
    inlineScript: |
      _zone_name=`echo $(_zone) | sed 's/\./\-/'`
      https_exists=`az cdn custom-domain show --endpoint-name $(_endpoint_name) -n $(_env)$(_site)-$_zone_name --profile-name $(_cdn_name) -g $(_rg_name) | jq '.customHttpsProvisioningState' -r`

      if [ $https_exists == "Enabled" ]; then
        echo "##[DEBUG] Custom https already enabled."
      else
        echo "##[DEBUG] Setting up custom https. If this step fails, you can manually enable Custom HTTPS for $(_endpoint_name) on the portal.azure.com dashboard."
        az cdn custom-domain enable-https --endpoint-name $(_endpoint_name) -n $(_env)$(_site)-$_zone_name --profile-name $(_cdn_name) -g $(_rg_name)
      fi

- pwsh: |
    $outputs = ConvertFrom-Json '$(outputConnectionString)'
    foreach ($output in $outputs.PSObject.Properties) {
          Write-Host "##vso[task.setvariable variable=_connectionstring]$($output.Value.value)"
    }
  displayName: 'Output parsed connection string'

- task: AzureCLI@1
  displayName: 'Enable static-website for storage account and set index to index.html'
  inputs:
    azureSubscription: '$(_service_connection)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob service-properties update --account-name ''$(_storage_name)'' --static-website  --index-document index.html'

- task: AzureCLI@1
  displayName: 'Upload storage content to static site'
  inputs:
    azureSubscription: '$(_service_connection)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob sync -s ''public'' -c ''$web'' --connection-string ''$(_connectionstring)'''

- task: AzureCLI@2
  displayName: 'Purge the site cache'
  inputs:
    azureSubscription: '$(_service_connection)'
    scriptType: shell
    scriptLocation: 'inlineScript'
    inlineScript: 'az cdn endpoint purge -g $(_rg_name) -n $(_endpoint_name) --profile-name $(_cdn_name) --content-paths "/*" --no-wait'

# Pull upstream to Bovey Test
# Run Gatsby Build (Drupal Source = Bovey Test) using submodule of gus
# Deploy built artifact from gatsby build to azure (Test)
# Run Gatsby Build (Drupal Source = Bovey Live) using submodule of gus
# Deploy built artifact from gatsby build to azure (Reference)
# Run visual regression tests (available via gus)
# Pull upstream to Bovey Live
# Run Gatsby Build (Drupal Source = Bovey Live) using submodule of gus

  # Publish artifact
- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourcesDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifact
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: build_artifact

# Clean up
- script: ./.ci/env/clean
  displayName: 'Clean up build environment'
  condition: always()
