# Build, test, and deploy the content hub.
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/php
#=========================================================================
# In addition to the environment variables defined in this file, also
# add the following variables in the Azure Pipelines UI.
#
# See: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
#
# TERMINUS_SITE:  Name of the Pantheon site to run tests on, e.g. my_site
# TERMINUS_TOKEN: The Pantheon machine token
# DEVOPS_TOKEN:   The Azure DevOps personal access token
# GIT_EMAIL:      The email address to use when making commits
#
# TEST_SITE_NAME: The name of the test site to provide when installing.
# ADMIN_PASSWORD: The admin password to use when installing.
# ADMIN_EMAIL:    The email address to give the admin when installing.
#=========================================================================

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  phpVersion: 7.2

steps:
- script: ./.ci/env/set
  displayName: 'Initialize build environment'

#- script: ./.ci/test/static/run
#  displayName: 'Static tests'

- script: ./.ci/build/php
  displayName: 'Build PHP'

- script: ./.ci/deploy/pantheon/dev-multidev
  displayName: 'Deploy to Pantheon'

- script: true
  displayName: 'Behat tests'

- script: true
  displayName: 'Visual regression test'

- script: true
  displayName: 'Composer lock updater'

- script: ./.ci/env/clean
  displayName: 'Clean up build environment'
  condition: always()
