#!/bin/bash

set -eo pipefail

#
# This script deploys the build artifact to Pantheon.
# On the master branch the dev environment is used.
# Otherwise a multidev environment is used.
#

# Set default branch
# TODO: Can this be taken from a system variable?
DEFAULT_BRANCH=master

# Authenticate with Terminus
$TERMINUS -n auth:login --machine-token="$TERMINUS_TOKEN"

# Prepare for Pantheon
composer run prepare-for-pantheon

# Install build tools plugin
composer run install-build-tools

if [[ $BUILD_SOURCEBRANCHNAME != $DEFAULT_BRANCH ]]
then
  # Create a new multidev environment (or push to an existing one)
  $TERMINUS -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes
else
  # Push to the dev environment
  $TERMINUS -n build:env:push "$TERMINUS_SITE.dev" --yes
fi

# Update the Drupal database
$TERMINUS -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- updatedb -y

# If exported configuration is available, then import it.
if [ -f "config/system.site.yml" ] ; then
  $TERMINUS -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- config-import --yes
fi

# Clear Drupal cache
$TERMINUS -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- cr

# Clear the environment cache
$TERMINUS -n env:clear-cache $TERMINUS_SITE.$TERMINUS_ENV

# Ensure secrets are set
$TERMINUS -n secrets:set "$TERMINUS_SITE.$TERMINUS_ENV" token "$DEVOPS_TOKEN" --file='devops-secrets.json' --clear --skip-if-empty

# Delete old multidev environments associated
# with a PR that has been merged or closed.
# TODO: Make this work for Azure DevOps
#$TERMINUS -n build:env:delete:pr $TERMINUS_SITE --yes
