#!/bin/bash

# Use PHP 7.2
sudo update-alternatives --set php /usr/bin/php$PHPVERSION
sudo update-alternatives --set phar /usr/bin/phar$PHPVERSION
sudo update-alternatives --set phpdbg /usr/bin/phpdbg$PHPVERSION
sudo update-alternatives --set php-cgi /usr/bin/php-cgi$PHPVERSION
sudo update-alternatives --set phar.phar /usr/bin/phar.phar$PHPVERSION
php -version

# Disable xdebug
sudo phpdismod -s cli xdebug

# Install Terminus
sudo apt update
sudo apt -y install php php-cli php-fpm php-json php-common php-mysql php-zip php-gd php-mbstring php-curl php-xml php-pear php-bcmath
curl -L https://github.com/pantheon-systems/terminus/releases/download/$(curl --silent "https://api.github.com/repos/pantheon-systems/terminus/releases/latest" | perl -nle'print $& while m{"tag_name": "\K.*?(?=")}g')/terminus.phar --output terminus
sudo install terminus /usr/local/bin

# Check Versions
composer --version
terminus --version
drush --version

# Configure Git user
git config --global user.email "$BUILD_REQUESTEDFOREMAIL"
git config --global user.name "$BUILD_REQUESTEDFORID"

# Authenticate terminus
terminus auth:login --machine-token="$TERMINUS_TOKEN" </dev/null
ssh-keygen -N "" -f ~/.ssh/id_rsa &&
terminus ssh-key:add ~/.ssh/id_rsa.pub </dev/null
