#!/bin/bash

# Use PHP 7.2
sudo update-alternatives --set php /usr/bin/php$PHPVERSION
sudo update-alternatives --set phar /usr/bin/phar$PHPVERSION
sudo update-alternatives --set phpdbg /usr/bin/phpdbg$PHPVERSION
sudo update-alternatives --set php-cgi /usr/bin/php-cgi$PHPVERSION
sudo update-alternatives --set phar.phar /usr/bin/phar.phar$PHPVERSION
php -version

# Disable xdebug
sudo phpdismod -s cli xdebug

# Install Terminus
sudo mkdir -p /opt/terminus &&
curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar &&
sudo php installer.phar install --install-dir=/opt/terminus --bin-dir=/usr/bin

# Check Versions
composer --version
terminus --version
drush --version

# Configure Git user
git config --global user.email "$BUILD_REQUESTEDFOREMAIL"
git config --global user.name "$BUILD_REQUESTEDFORID"

# Authenticate terminus
terminus auth:login --machine-token="$TERMINUS_TOKEN" </dev/null
ssh-keygen -N "" -f ~/.ssh/id_rsa &&
terminus ssh-key:add ~/.ssh/id_rsa.pub </dev/null
