asset_bank.settings:
  type: config_object
  mapping:
    asset_bank:
      type: config_object
      mapping:
        url:
          type: uri
          label: 'Asset Bank URL'
        name:
          type: string
          label: 'Asset Bank Name'
