#!/bin/bash

set -eo pipefail

echo "##vso[task.setvariable variable=_pantheonsitelabel]$(PantheonSiteLabel)"
echo "##vso[task.setvariable variable=_rg_name]$(_env)$(_site)rg"
echo "##vso[task.setvariable variable=_storage_name]$(_env)$(_site)storage"
echo "##vso[task.setvariable variable=_cdn_name]$(_env)$(_site)cdn"
echo "##vso[task.setvariable variable=_endpoint_name]$(_env)$(_site)endpoint"

