#!/bin/bash

set -eo pipefail

echo "##vso[task.setvariable variable=_site]$(Site)"
# echo "##vso[task.setvariable variable=_env]$(Env)"
echo "##vso[task.setvariable variable=_zone]$(Zone)"
echo "##vso[task.setvariable variable=_pantheonsitelabel]$(PantheonSiteLabel)"
echo "##vso[task.setvariable variable=_rg_name]$(Env)$(Site)rg"
echo "##vso[task.setvariable variable=_storage_name]$(Env)$(Site)storage"
echo "##vso[task.setvariable variable=_cdn_name]$(Env)$(Site)cdn"
echo "##vso[task.setvariable variable=_endpoint_name]$(Env)$(Site)endpoint"

