#!/bin/bash

set -eo pipefail

#
# This script runs cleanup after Behat tests complete.
#

# Authenticate with Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN" </dev/null

# Restore the DB backup made before testing
#terminus -n backup:restore $TERMINUS_SITE.$TERMINUS_ENV --element=database --yes

# Clear Drupal cache
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" cr </dev/null

# Clear site cache
terminus -n env:clear-cache $TERMINUS_SITE.$TERMINUS_ENV </dev/null
