#!/bin/bash

set -eo pipefail

# Environment
RESULTS=${COMMON_TESTRESULTSDIRECTORY:-TestResults}

#
# This script runs cleanup after Behat tests complete.
#

# Authenticate with Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN" </dev/null

# Restore the DB backup made before testing
#terminus -n backup:restore $TERMINUS_SITE.$TERMINUS_ENV --element=database --yes

# Clear Drupal cache
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" cr </dev/null

# Clear site cache
terminus -n env:clear-cache $TERMINUS_SITE.$TERMINUS_ENV </dev/null

# Export tests
if [ -n "$AGENT_ID" ]
then
  vendor/bin/behat --config=tests/ug/config-ci.yml --format junit --out ${RESULTS} || true
else
  vendor/bin/behat --config=tests/ug/config-ci.yml 
fi
