#!/bin/bash

set -eo pipefail

#
# This script runs static tests which
# can be performed without code execution.
#
# Some example are code sniffing and unit testing
#

# Run unit tests
composer -n unit-test

# Delete and reset the web directory
# This is necessary so that third-party
# dependencies are not tested
git clean -fdX web

# Lint php code for syntax errors
composer -n lint

# Check coding standards
composer -n code-sniff
